# Generated by Django 4.0.5 on 2023-01-04 07:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ToDoList', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list',
            options={'ordering': ['complete']},
        ),
        migrations.RemoveField(
            model_name='list',
            name='task',
        ),
        migrations.AddField(
            model_name='list',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='list',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 1, 4, 7, 1, 3, 791141, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='list',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='list',
            name='tittle',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='list',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
